name = "tirta-afiat-booking"
main = "src/index.js"
compatibility_date = "2024-09-23"

[vars]
ADMIN_TOKEN = "admin123"

[[d1_databases]]
binding = "DB"
database_name = "tirta-afiat"
database_id = "a584382c-8172-409d-b35f-68833eb53c32"

[env.production]
vars = { ADMIN_TOKEN = "admin123" }
